# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 14:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 13, 14, 30, 28, 728589, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
